update prisma web
H-chauvet/RISU pull request #104
Opened 2023-11-19 21:15 UTC by invpuppet

all english, norm, addition to container

2023-11-20 01:27 UTC, tbellicha reviewed
Did you check the fields (if needed) in the code as well ?

2023-11-21 00:46 UTC, invpuppet commented
I checked before push but if i left some don't hesitate to tell me

2023-11-21 05:53 UTC, tbellicha commented
I meant, since you changed some names in the schema, did you check all the possible usages of these elemnts ?

2023-11-21 10:18 UTC, invpuppet commented
my bad i left some data that were not with the good names

2023-11-22 00:04 UTC, tbellicha requested changes

2023-11-22 00:04 UTC, tbellicha commented on Configurateur/back/routes/contact.js
> +    const { firsName, lastName, email, message } = req.body
firsName ?

2023-11-22 00:04 UTC, tbellicha commented on Configurateur/back/routes/contact.js
> +    const msg = await contactCtrl.registerMessage({ lastName, firsName, email, message })
firsName ?

2023-11-22 02:57 UTC, tbellicha approved these changes

2023-11-22 22:40 UTC, merged