Feature/261
H-chauvet/RISU pull request #144
Opened 2023-12-23 21:48 UTC by Louismaestre

Display items in the container for the admin to delete it easier

2023-12-30 09:02 UTC, CedricCORGE requested changes

2023-12-30 09:02 UTC, CedricCORGE commented on Configurateur/front/lib/screens/container-list/item-list/item_list.dart
> +      // );
pourquoi c'est en commentaire ?

2024-01-02 22:09 UTC, Louismaestre commented on Configurateur/back/controllers/items.js
> +}
Erreur d'inattention de ma part, j'ai supprimé la fonction useless

2024-01-02 22:18 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/item-list/item_list.dart
> +      // );
Oublie de ma part, tout ceci est fix

2024-01-03 17:13 UTC, CedricCORGE approved these changes

2024-01-04 07:54 UTC, merged