Feature/269
H-chauvet/RISU pull request #145
Opened 2023-12-25 01:43 UTC by Louismaestre

2023-12-28 20:21 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/container/container_state.dart
> +        print('Error getContainer(): ${response.statusCode}');
So, no information to the user that the request has failed ?

2023-12-28 20:21 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/container/container_state.dart
> +      print('Error getContainer(): $e');
same here

2023-12-29 09:32 UTC, 31Nathan requested changes

2023-12-29 09:32 UTC, 31Nathan commented on Application/mobile/app_code/test/container_test.dart
![image](https://github.com/H-chauvet/RISU/assets/72010794/89c10202-f922-439f-b9b1-1ed8b87e5034)
Missing a lot of tests, please test your code

2024-01-02 13:13 UTC, tbellicha approved these changes

2024-01-08 01:38 UTC, merged

2024-01-08 01:42 UTC, invpuppet commented on Application/server/server.js
> -app.get('/api/container/listall', async (req, res) => {
where is that route now