[FIX] mobile: container details to article details
H-chauvet/RISU pull request #167
Opened 2024-01-19 04:26 UTC by invpuppet

fix route (become 'get' routes)

add tests for (front and back) :
- container details
- article list
- article list data
- article details

fix theme colors of the aforementioned pages

2024-01-19 07:19 UTC, 31Nathan reviewed
Overall, seems ok, just need to know why the article.dart was deleted

2024-01-20 04:10 UTC, invpuppet commented
![image](https://github.com/H-chauvet/RISU/assets/62613130/302563f7-eb77-4a82-b0b3-53b74e8034a0)
![image](https://github.com/H-chauvet/RISU/assets/62613130/0762edee-bc2a-42dd-b3bc-7b8111ad8871)
![image](https://github.com/H-chauvet/RISU/assets/62613130/6ccc1907-40d7-43d2-b720-361457aef172)

2024-01-20 04:14 UTC, tbellicha requested changes

2024-01-20 04:14 UTC, tbellicha commented on Application/mobile/app_code/test/article_details_test.dart
> +}
Missing new line

2024-01-20 04:14 UTC, tbellicha commented on Application/mobile/app_code/test/article_list_test.dart
> +}
Missing new line

2024-01-20 04:14 UTC, tbellicha commented on Application/server/server.js
> +      console.log("container/details")
Remove useless log

2024-01-20 04:14 UTC, tbellicha commented on Application/server/server.js
> +      console.log("container/articleList")
Remove useless log

2024-01-20 04:14 UTC, tbellicha commented on Application/server/server.js
>          return res.status(204).json({ message: 'Container doen\'t have items' })
doesn't*

2024-01-20 04:14 UTC, tbellicha commented on Application/server/server.js
>        res.status(401).send('An error occurred')
use return, 2 lines above too

2024-01-20 04:14 UTC, tbellicha commented on Application/server/server.js
> +  })
why these spaces ?
LIne 627 too

2024-01-20 04:14 UTC, tbellicha commented on Application/server/tests/apiArticle.test.js
> +})
Missing new line

2024-01-20 04:14 UTC, tbellicha commented on Application/server/tests/apiContainer.test.js
> +})
Missing new line

2024-01-20 18:06 UTC, merged