Feature/281
H-chauvet/RISU pull request #177
Opened 2024-01-24 03:05 UTC by invpuppet

2024-01-24 05:09 UTC, invpuppet commented
[Screen_recording_20240124_065729.webm](https://github.com/H-chauvet/RISU/assets/62613130/d33528d6-5a9c-4960-b1a8-b22bbed31981)

2024-01-24 05:10 UTC, invpuppet commented
[Screen_recording_20240124_065729.webm](https://github.com/H-chauvet/RISU/assets/62613130/e962aa0d-02d8-48e8-8b73-cdb51f1ebaf6)

2024-01-24 05:42 UTC, tbellicha commented
> Screen_recording_20240124_065729.webm

Wait what, there is no message telling the user that the article have been successfully given back, and the user stays on the page ?

2024-01-24 05:50 UTC, tbellicha requested changes

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +        print("success");
useless debug printing

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +          await MyAlertDialog.showInfoAlertDialog(
"showInfo" while the title is "Error" ?

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +                            color: themeProvider.currentTheme.brightness ==
Use the theme colors

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +                                          color: themeProvider.currentTheme
Use the theme colors

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +                                                      .brightness ==
Use the theme colors

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +                                          color: themeProvider.currentTheme
Use theme colors

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +                                          color: themeProvider.currentTheme
Use theme colors

2024-01-24 05:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +                        message: 'Voules-vous rendre votre location ?',
"Confirmer le rendu de l'article" might be better ?

2024-01-24 05:50 UTC, tbellicha commented on Application/server/prisma/schema.prisma
> +	finished			Boolean		@default(false)
"ended" might be better ?

2024-01-24 05:50 UTC, tbellicha commented on Application/server/server.js
> +        return res.status(401).send('location not found')
Write your sentences with uppercase

2024-01-24 05:50 UTC, tbellicha commented on Application/server/server.js
> +      if (!req.body.rentId || req.params.rentId == '') {
body and params ?

2024-01-24 05:50 UTC, tbellicha commented on Application/server/server.js
> +app.post('/api/rent/return',
"/api/rent/:rentId/return" would be better

2024-01-25 17:51 UTC, tbellicha approved these changes

2024-01-25 17:52 UTC, merged