[ADD] add third theme : 'Système'
H-chauvet/RISU pull request #218
Opened 2024-02-02 09:56 UTC by hugolopespinto

i added a third theme + changed the way of switching theme, (toggleT

https://github.com/H-chauvet/RISU/assets/72020673/a91aa439-813c-4415-828d-bc6eef4fad47

heme to setTheme)

2024-02-05 04:36 UTC, H-chauvet commented on Application/mobile/app_code/lib/main.dart
> +//bool isDarkTheme = false;
Remove useless comment

2024-02-05 04:37 UTC, H-chauvet commented on Application/mobile/app_code/lib/main.dart
> +  //isDarkTheme = prefs.getBool('isDarkTheme') ?? false;
Same here, remove useless comment

2024-02-05 04:37 UTC, H-chauvet requested changes
Make the requested changes and you can submit again your code

2024-02-05 05:49 UTC, tbellicha requested changes

2024-02-05 05:49 UTC, tbellicha commented on Application/mobile/app_code/lib/main.dart
> +String appTheme = 'Clair';
Don't use a String, use an enum or a Map

2024-02-05 05:49 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/settings/settings_pages/theme/theme_settings_page.dart
> +  const ThemeChangeModalContent({super.key});
Put a comma after the key

2024-02-07 17:59 UTC, H-chauvet approved these changes
Nothing wrong for me

2024-02-09 12:47 UTC, merged