[ADD] initPage + space between tests
H-chauvet/RISU pull request #226
Opened 2024-02-09 21:17 UTC by hugolopespinto

add space between tests + use of initPage function

2024-02-09 21:56 UTC, tbellicha requested changes

2024-02-09 21:56 UTC, tbellicha commented on Application/mobile/app_code/test/theme_test.dart
> +      await tester.pumpWidget(initPage(
That's not how we use initPage, read the function or ask question if you don't understand

2024-02-09 22:54 UTC, tbellicha approved these changes

2024-02-10 04:51 UTC, invpuppet approved these changes
seems good for me

2024-02-10 15:46 UTC, H-chauvet approved these changes
Good

2024-02-10 20:15 UTC, tbellicha approved these changes

2024-02-12 06:44 UTC, merged