Feature/invoice location confirmation
H-chauvet/RISU pull request #238
Opened 2024-02-19 12:48 UTC by hugolopespinto

When the user rent an article, he will receive an email saying that the rent is confirmed, an invoice will also be saved in the database. The user can receive the invoice clicking in the button  dedicated to it, the button is in the confirm rent page and in the details of the location (accessible from the locations history).

2024-02-19 17:35 UTC, invpuppet requested changes

2024-02-19 19:44 UTC, invpuppet approved these changes

2024-02-19 20:16 UTC, 31Nathan requested changes
Missing tests for the back end part

2024-02-19 20:16 UTC, 31Nathan commented on Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
> +      final response = await http.get(
get request for not getting anything ? Change the request to be coherent

2024-02-19 20:16 UTC, 31Nathan commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +      final response = await http.get(
Same here

2024-02-19 20:16 UTC, 31Nathan commented on Application/mobile/app_code/test/confirm_rent_test.dart
> +    await tester.tap(homeButton, warnIfMissed: false);
Not a good thing the "warnIfMissed"

2024-02-19 20:16 UTC, 31Nathan commented on Application/mobile/app_code/test/confirm_rent_test.dart
> +    await tester.tap(invoiceButton, warnIfMissed: false);
Same

2024-02-19 20:16 UTC, 31Nathan commented on Application/mobile/app_code/test/rent_return_test.dart
> +      /*await tester.tap(sendInvoiceButton);
Why push commented lines ?

2024-02-19 20:16 UTC, 31Nathan commented on Server/routes/Mobile/rent.js
> +function formatDate(date) {
Can be used in other file, create a specific file for it that can be imported from anywhere

2024-02-19 20:16 UTC, 31Nathan commented on Server/routes/Mobile/rent.js
> +function drawTable(doc, tableData) {
Same here

2024-02-19 20:16 UTC, 31Nathan commented on Server/routes/Mobile/rent.js
> +      sendInvoice(location.invoice, user.email);
need to await

2024-02-19 21:05 UTC, tbellicha requested changes

2024-02-19 21:05 UTC, tbellicha commented on Server/routes/Mobile/utils.js
> +};
New line missing

2024-02-19 23:20 UTC, invpuppet requested changes

2024-02-19 23:20 UTC, invpuppet commented on Server/routes/Mobile/utils.js
> +function formatDate(date) {
no coverage directly on this file (the one on the branch come from the test on the invoice route)

2024-02-19 23:20 UTC, invpuppet commented on Server/routes/Mobile/rent.js
> +router.put('/:locationId/invoice',
you only test the case where there is no error

2024-02-20 00:38 UTC, tbellicha requested changes

2024-02-20 00:38 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
> +      final response = await http.put(
Put is to update, not to create

2024-02-20 00:38 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/return_state.dart
> +      final response = await http.put(
Put is to update, not to create

2024-02-20 00:38 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/rent/confirm/confirm_rent_state.dart
> +                        key: const Key('return-rent-button-receive_invoice'),
Bad Key

2024-02-20 01:18 UTC, invpuppet approved these changes
good for me

2024-03-05 21:13 UTC, H-chauvet commented on Server/routes/Mobile/rent.js
> +        text: 'Votre location a bien été enregistrée. \nVous avez loué l\'article ' + itemId + ' pour une durée de ' + duration + ' heures le ' + formattedDate + ' dans le conteneur situé à l\'addres
Adresse et non pas "Addresse"

2024-03-05 21:14 UTC, H-chauvet submitted a review, later dismissed
Change the word "Addresse" to "Adresse"

2024-03-07 14:02 UTC, 31Nathan requested changes

2024-03-10 14:42 UTC, 31Nathan requested changes
Good invoice directory, now use it and name correctly your file

2024-03-10 14:42 UTC, 31Nathan commented on Server/invoice/utils.js
rent utils and utils in the same directory ? Merge the files or rename it correctly

2024-03-10 14:42 UTC, 31Nathan commented on Server/routes/Mobile/createInvoice.js
> +        //", " +
Useless comment

2024-03-10 14:42 UTC, 31Nathan commented on Server/routes/Mobile/createInvoice.js
It is in the routes directory without routes, should be on the invoice one

2024-03-11 18:20 UTC, 31Nathan approved these changes

2024-03-11 18:27 UTC, merged