[DOC] Server documentation
H-chauvet/RISU pull request #260
Opened 2024-03-04 16:49 UTC by 31Nathan

Improving the documentation of the server

2024-03-11 20:15 UTC, tbellicha requested changes

2024-03-11 20:15 UTC, tbellicha commented on Server/controllers/Web/messages.js
> + * @param {number} id of the message to be deleted
No throws ?

2024-03-12 16:11 UTC, 31Nathan commented on Server/controllers/Common/container.js
> + * @returns the container object with its items
Yes it return the container with items on .items attributes

2024-03-12 16:15 UTC, CedricCORGE commented on Server/controllers/Mobile/user.js
> + * @returns none
if none is return why is it a return in the method ?

2024-03-12 16:15 UTC, CedricCORGE commented on Server/documentation.example.js
> + * @returns the nbr given in param
in sentence it's better to say number than the variable name "nbr"

2024-03-12 16:45 UTC, CedricCORGE approved these changes

2024-03-12 17:06 UTC, H-chauvet approved these changes
Good for me

2024-03-12 17:58 UTC, tbellicha approved these changes

2024-03-12 17:59 UTC, merged