264 item opinions
H-chauvet/RISU pull request #274
Opened 2024-03-16 22:15 UTC by hugolopespinto

rework the opinion system, now they are linked to an item, the user can add opinions to an item (with note and comment), and can also update or remove it (if he created it)

2024-03-18 08:44 UTC, invpuppet requested changes

2024-03-18 08:44 UTC, invpuppet commented on Server/controllers/Mobile/opinion.js
> +}
missing new line

2024-03-18 08:44 UTC, invpuppet commented on Server/prisma/schema.prisma
>      date    DateTime
maybe update Opinions_Mobile to add a real prisma relation between it and User_Mobile

2024-03-18 10:05 UTC, CedricCORGE requested changes

2024-03-18 10:05 UTC, CedricCORGE commented on Application/mobile/app_code/lib/pages/opinion/opinion_state.dart
> +                  // Champ de note
useless comment

2024-03-18 10:05 UTC, CedricCORGE commented on Application/mobile/app_code/test/opinion_test.dart
> +    /*testWidgets('find opinions pages buttons', (WidgetTester tester) async {
useless commented test to remove

2024-03-18 10:33 UTC, invpuppet approved these changes
good for me

2024-03-18 11:11 UTC, CedricCORGE approved these changes

2024-03-18 17:02 UTC, 31Nathan requested changes

2024-03-18 17:02 UTC, 31Nathan commented on Server/controllers/Mobile/user.js
> +exports.getFullName = (userId) => {
Missing doc

2024-03-18 17:02 UTC, 31Nathan commented on Server/prisma/schema.prisma
> +    item    Item     @relation(fields: [itemId], references: [id])
Identation

2024-03-18 17:02 UTC, 31Nathan commented on Server/routes/Mobile/opinion.js
> +// get all opinions from an item (can be filtered by note)
The doc does not go there

2024-03-18 17:02 UTC, 31Nathan commented on Server/routes/Mobile/opinion.js
> +// add an opinion to an item
Same here

2024-03-18 17:02 UTC, 31Nathan commented on Server/routes/Mobile/opinion.js
> +router.delete('/:opinionId',
Again

2024-03-18 17:02 UTC, 31Nathan commented on Server/routes/Mobile/opinion.js
> +// update an opinion
And Again

2024-03-20 13:52 UTC, 31Nathan approved these changes

2024-03-20 14:01 UTC, merged