284 token handling
H-chauvet/RISU pull request #286
Opened 2024-04-08 13:01 UTC by hugolopespinto

The user can now select a checkbox to avoid having to log in again every 20 minutes. The token is updated automatically when it expires if the checkbox is active when the user logs in.

front updates : (checkbox with the text to stay connected)
![image](https://github.com/H-chauvet/RISU/assets/72020673/7f3e6b37-d99f-4ef1-a7ef-1b63fb554a85)
![image](https://github.com/H-chauvet/RISU/assets/72020673/7a57f6b9-7733-4a56-b6db-a6bb6b807c36)
![image](https://github.com/H-chauvet/RISU/assets/72020673/3ab3e354-384e-4c4e-99e2-331dc7dabebb)
![image](https://github.com/H-chauvet/RISU/assets/72020673/95979a99-d0f7-4ede-8967-cf9c1b6f34bc)

tests :
back:
![image](https://github.com/H-chauvet/RISU/assets/72020673/9712ccd1-7b11-4b08-8adf-da3917991a5c)
front:
![image](https://github.com/H-chauvet/RISU/assets/72020673/679639c7-a2ae-4480-b233-8be4d922092d)
![image](https://github.com/H-chauvet/RISU/assets/72020673/20f8e582-2af3-4d98-9a4d-61d7cc101302)

2024-04-08 19:58 UTC, CedricCORGE approved these changes

2024-04-09 07:29 UTC, 31Nathan requested changes
Small things, do not forget to update the coverage in the PR, otherwise very good job !

2024-04-09 07:29 UTC, 31Nathan commented on Server/middleware/Mobile/jwt.js
> + * @param {*} user user object
Wrong documentation

2024-04-09 07:29 UTC, 31Nathan commented on Server/routes/Mobile/auth.js
> +      console.log('longTerm', longTerm);
This log should be kept ?

2024-04-10 18:28 UTC, tbellicha requested changes
Don't merge, you didn't do it correctly

2024-04-15 06:24 UTC, 31Nathan approved these changes
LGTM

2024-04-15 13:18 UTC, CedricCORGE requested changes

2024-04-15 13:18 UTC, CedricCORGE commented on Server/middleware/Mobile/jwt.js
> +  return crypto.randomBytes(64).toString('hex');
it works but why not using jwt library like for accessToken ?

2024-04-15 13:18 UTC, CedricCORGE commented on Server/routes/Mobile/auth.js
> +        longTerm = false;
why not use the value of req.body.longTerm instead of hard coded false ?

2024-04-15 15:41 UTC, tbellicha requested changes

2024-04-16 04:52 UTC, CedricCORGE requested changes

2024-04-16 04:52 UTC, CedricCORGE commented on Application/mobile/app_code/lib/l10n/app_fr.arb
> +  "french": "Français",
I preshot the review of Tanguy, even in french english text should be "English" instead of "Anglais"

2024-04-16 04:52 UTC, CedricCORGE commented on Server/docs/paths/Mobile/auth/login.js
> +            type: 'string',
isn't a bool now ?

2024-04-16 04:52 UTC, CedricCORGE commented on Server/tests/mobile/login.test.js
maybe add somes cases of invalid call, where you failed status

2024-04-17 09:21 UTC, CedricCORGE approved these changes

2024-04-17 14:33 UTC, tbellicha requested changes
You have to reverse the changes you did for the language, let the languages wrote in their language

2024-04-17 17:50 UTC, tbellicha approved these changes

2024-04-17 17:54 UTC, merged