212 mobile favorite articles
H-chauvet/RISU pull request #295
Opened 2024-04-17 02:26 UTC by invpuppet

The user can now add article as favorites from the ArticleDetails page (connexion required).
From the profile page, the user can now access the MyFavorites page where he can see all his favorites, access to the details of a related article or remove a favorite from the list.

![image](https://github.com/H-chauvet/RISU/assets/62613130/802aaa2f-e65d-4aaf-bd15-d05d09062955)
![image](https://github.com/H-chauvet/RISU/assets/62613130/1c74750d-c04f-4595-bb81-e6f8030e60a5)
![image](https://github.com/H-chauvet/RISU/assets/62613130/e48472df-bf50-41a9-8858-d72a173092b6)

Tests Front (the majority of the new content are made of server calls):
![image](https://github.com/H-chauvet/RISU/assets/62613130/929a1d23-808e-4da4-82a7-543be8eebf7f)

Tests Back:
![image](https://github.com/H-chauvet/RISU/assets/62613130/859e28f2-eca7-4ca2-b554-11176ec3a147)

2024-04-17 02:44 UTC, tbellicha reviewed
I would prefer the like button on the AppBar in the ArticleDetails page. Then in the favorites list, I would put a '>' icon on the right of the card, then I would put the heart on the top-left of the card, and not of the image of the article

2024-04-17 14:07 UTC, 31Nathan requested changes
Missing routes documentation, check doc directory

2024-04-17 14:07 UTC, 31Nathan commented on Application/mobile/app_code/test/favorite_test.dart
Maybe add tap on button if possibke

2024-04-17 14:15 UTC, invpuppet commented on Application/mobile/app_code/test/favorite_test.dart
since i get no favorites since there is no server connection here no card gets generated

2024-04-17 23:12 UTC, H-chauvet approved these changes
Good, don't forget documentation if missing

2024-04-17 23:14 UTC, tbellicha requested changes

2024-04-17 23:14 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/container/container_list.dart
> +    double price = json['price'] != null ? json['price'].toDouble() : 0.0;
You're initializing a variable without using it after

2024-04-17 23:14 UTC, tbellicha commented on Server/routes/Mobile/favorites.js
> +module.exports = router
missing new line

2024-04-18 00:07 UTC, tbellicha approved these changes

2024-04-18 07:58 UTC, 31Nathan approved these changes

2024-04-18 08:06 UTC, 31Nathan approved these changes

2024-04-18 08:13 UTC, merged