269 web responsive pages
H-chauvet/RISU pull request #297
Opened 2024-04-17 13:59 UTC by CedricCORGE

2024-05-10 15:27 UTC, 31Nathan approved these changes

2024-05-10 15:36 UTC, 31Nathan requested changes

2024-05-10 15:36 UTC, 31Nathan commented on Configurateur/front/lib/screens/container-creation/maps_screen/maps_screen.dart
> +    //checkToken();
Why is that ?

2024-05-10 15:36 UTC, 31Nathan commented on Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
> +import '../../../network/informations.dart';
package:

2024-05-10 15:36 UTC, 31Nathan commented on Configurateur/front/lib/screens/container-creation/recap_screen/recap_screen.dart
> +import '../../../styles/themes.dart';
package:

2024-05-10 15:36 UTC, 31Nathan commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
> +import '../../../components/progress_bar.dart';
package:

2024-05-13 10:43 UTC, H-chauvet commented on Configurateur/front/lib/components/container.dart
> +                        "Adresse : aucune address",
Franglais à éviter, typographie pas respectée

2024-05-13 10:44 UTC, H-chauvet commented on Configurateur/front/lib/components/container.dart
> +                        "Ville : pas de ville associée",
Typographie pas respectée

2024-05-13 10:47 UTC, H-chauvet requested changes
Changes the typo where I commented and it's gonna be good

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/components/recap_panel.dart
> +                constraints: BoxConstraints(minWidth: 7.0.w, maxWidth: 7.0.w),
Why you don't add the value of  minWidth and maxWidth in the globalStyle ?

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/components/recap_panel.dart
> +                constraints: BoxConstraints(minWidth: 5.0.w),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/components/recap_panel.dart
> +                          BoxConstraints(minWidth: 7.0.w, maxWidth: 7.0.w),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/components/recap_panel.dart
>                    padding: const EdgeInsets.only(right: 10, bottom: 10),
Same with right and bottom

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/components/recap_panel.dart
>                height: 10,
same with height

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/contact/contact.dart
> +            widthFactor: 0.8,
why you don't add de widthFactor in the globalStyle or is own style file like the others ?

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/confirmation_screen/confirmation_screen.dart
>                  heightFactor: 0.7,
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
>                      const SizedBox(
Maybe you can put the value of sizebox in the globalStyle and add it to all of the others

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
> +              const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/container_creation/container_creation.dart
> +              const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
>                    const SizedBox(height: 50),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
>                    const SizedBox(height: 20),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/payment_screen/payment_screen.dart
>                    const SizedBox(height: 100),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/recap_screen/recap_screen.dart
>                  const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/recap_screen/recap_screen.dart
>                  const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
>            const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
>                      const SizedBox(width: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
>                  const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
>                  const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
>                      const SizedBox(width: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-creation/shape_screen/shape_screen.dart
>                    const SizedBox(
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/container_list.dart
>                      const SizedBox(height: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/container_list.dart
>                      const SizedBox(height: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/container_list.dart
> +                    const SizedBox(height: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/container_list.dart
>                      const SizedBox(height: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/container_list.dart
>                      const SizedBox(height: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/container-list/container_list.dart
> +                    const SizedBox(height: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/login/login.dart
> -                        padding: EdgeInsets.all(10.0),
maybe you can add the value of the padding in style file

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/password-recuperation/password_recuperation.dart
> +                const SizedBox(height: 10),
Add in gobal style

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/password-recuperation/password_recuperation.dart
> +                const SizedBox(height: 20),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/password-recuperation/password_recuperation.dart
> +                      const SizedBox(width: 10.0),
same

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/password-recuperation/password_recuperation.dart
> +                        height: 20.0,
maybe you can put the values in style file

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/password-recuperation/password_recuperation.dart
> +                const SizedBox(height: 20.0),
Add in global style file

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/register-confirmation/confirmed_user.dart
> +              SizedBox(
Add in global style file

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/register-confirmation/register_confirmation.dart
>                          padding: const EdgeInsets.all(10.0),
Add in global style file

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/lib/screens/save_container/my_container.dart
>              const SizedBox(height: 20),
Add in global style file

2024-05-13 18:57 UTC, Louismaestre commented on Configurateur/front/pubspec.lock
I think it's a mistake

2024-05-13 19:05 UTC, H-chauvet approved these changes

2024-05-13 20:40 UTC, tbellicha approved these changes
LGTM

2024-05-14 14:51 UTC, merged