[UPDATE] In the invoice, heures -> durée and add heures / heure
H-chauvet/RISU pull request #310
Opened 2024-04-18 23:01 UTC by hugolopespinto

modification de la facture (Quantité -> Durée) + ajouté de l'unité
![image](https://github.com/H-chauvet/RISU/assets/72020673/623538ad-a197-415e-9a27-0ee4239ca1fc)

Supression du refreshToken en base de données et dans l'app ce qui résout le problème de l'utilisateur qui reste connecté (sans cocher la case pour rester connecté) s'il s'est déjà connecté (en cochant la case pour rester connecté) auparavant.

2024-04-19 02:02 UTC, tbellicha requested changes

2024-04-19 02:02 UTC, tbellicha commented on Server/controllers/Mobile/user.js
> +}
missing new line

2024-04-19 06:26 UTC, 31Nathan approved these changes

2024-04-20 09:42 UTC, invpuppet approved these changes

2024-04-20 09:45 UTC, H-chauvet approved these changes
Good

2024-04-20 09:45 UTC, merged