[MOBILE] Handling of deleted data
H-chauvet/RISU pull request #324
Opened 2024-05-09 15:56 UTC by 31Nathan

Now when a user is deleted every data is cleaned to lighten the database and to ensure no bug can appear due to residual data.
Closes #253

2024-05-09 16:00 UTC, invpuppet requested changes
missing tests and some new line

2024-05-09 16:00 UTC, invpuppet commented on Server/controllers/Common/tickets.js
> +}
missing new line

2024-05-09 16:00 UTC, invpuppet commented on Server/controllers/Mobile/cleandata.js
> +}
missing new line

2024-05-09 16:00 UTC, invpuppet commented on Server/controllers/Mobile/favorites.js
> +}
missing new line

2024-05-09 16:00 UTC, invpuppet commented on Server/controllers/Mobile/rent.js
> +}
missing new line

2024-05-09 17:10 UTC, invpuppet submitted a review, later dismissed

2024-05-10 07:56 UTC, invpuppet approved these changes

2024-05-10 11:10 UTC, CedricCORGE approved these changes

2024-05-10 11:16 UTC, merged