Unit testing/mobile front/hugo
H-chauvet/RISU pull request #334
Opened 2024-05-18 00:45 UTC by hugolopespinto

.Add News tests in the front mobile
pages: item opinions, favorites

![image](https://github.com/H-chauvet/RISU/assets/72020673/79a241f0-443a-4eed-8595-4d7f2b03fcad)

2024-05-18 06:13 UTC, CedricCORGE approved these changes

2024-05-18 06:16 UTC, 31Nathan requested changes
Small changes

2024-05-18 06:16 UTC, 31Nathan commented on Application/mobile/app_code/lib/pages/article/favorite/favorite_page.dart
> +  final List<dynamic> favorites;
prefix them with test to ensure the understanding of it

2024-05-18 06:16 UTC, 31Nathan commented on Application/mobile/app_code/lib/pages/article/favorite/favorite_state.dart
> +          print(favorites);
Remove debug

2024-05-18 06:16 UTC, 31Nathan commented on Application/mobile/app_code/lib/pages/opinion/opinion_page.dart
> +  final List<dynamic> opinions;
Same here, prefix them with tests

2024-05-19 11:30 UTC, 31Nathan approved these changes

2024-05-19 11:42 UTC, merged