354 web download apk from the website
H-chauvet/RISU pull request #357
Opened 2024-06-16 13:59 UTC by H-chauvet

2024-06-16 14:27 UTC, 31Nathan requested changes
Missing doc for the route

2024-06-16 15:07 UTC, 31Nathan approved these changes

2024-06-16 15:26 UTC, CedricCORGE requested changes

2024-06-16 15:26 UTC, CedricCORGE commented on Application/mobile/Dockerfile
> +RUN ls -l /apk/
if it's debug, we don't need it anymore

2024-06-16 15:26 UTC, CedricCORGE commented on Application/mobile/Dockerfile
> +RUN ls -l build/app/outputs/flutter-apk/
if it's debug, we don't need it anymore

2024-06-16 15:26 UTC, CedricCORGE commented on Configurateur/front/lib/components/custom_header.dart
we didn't say that it's would be better to do the download on the showcase website ?

2024-06-16 15:52 UTC, H-chauvet commented on Configurateur/front/lib/components/custom_header.dart
Showcase website is not accessible to the public, risu website is

2024-06-17 12:22 UTC, CedricCORGE approved these changes

2024-06-17 12:34 UTC, merged