383 image principale et secondaire articles
H-chauvet/RISU pull request #384
Opened 2024-07-14 10:10 UTC by hugolopespinto

- [ ] Boutons pour changer les images
- [ ] Indicateurs ronds pour les images
- [ ] gestion des différentes images

2024-07-22 08:32 UTC, invpuppet requested changes

2024-07-22 08:32 UTC, invpuppet commented on Application/mobile/app_code/lib/l10n/app_en.arb
> -  "opinions": "Opinions",
Why delete this ?

2024-07-22 08:32 UTC, invpuppet commented on Application/mobile/app_code/lib/l10n/app_fr.arb
> -  "opinions": "Avis",
Why delete this ?

2024-07-22 11:33 UTC, hugolopespinto commented on Application/mobile/app_code/lib/l10n/app_en.arb
> -  "opinions": "Opinions",
i added it again

2024-07-22 11:33 UTC, hugolopespinto commented on Application/mobile/app_code/lib/l10n/app_fr.arb
> -  "opinions": "Avis",
i added it again

2024-07-23 13:38 UTC, CedricCORGE approved these changes

2024-07-24 11:17 UTC, invpuppet approved these changes

2024-07-25 11:11 UTC, tbellicha requested changes
TU Front Mobile

2024-08-26 09:45 UTC, closed without merging