405 mobile faq page
H-chauvet/RISU pull request #406
Opened 2024-08-19 16:44 UTC by hugolopespinto

![image](https://github.com/user-attachments/assets/3314076a-290f-4711-bb09-6d0745b97e77)
![image](https://github.com/user-attachments/assets/3251a556-0676-446f-8a7c-d085d6da4d1f)
![image](https://github.com/user-attachments/assets/9daac2d1-8598-4516-9cad-0809173cab47)

2024-08-29 11:32 UTC, 31Nathan reviewed
Check the message on discord
Title and order of the new page
Otherwise seems good !

2024-08-31 11:11 UTC, Louismaestre reviewed
Same as Nathan and also I think the title must be on the left of the page

2024-08-31 12:21 UTC, Louismaestre approved these changes

2024-08-31 13:41 UTC, CedricCORGE requested changes

2024-08-31 13:41 UTC, CedricCORGE commented on Application/mobile/app_code/lib/l10n/app_en.arb
> +  "faqTitle": "Hi {name},\nhow can we\nhelp you?",
I don't think '\n' should be in translation, should be a width cap in the user interface instead of '\n'. And it's looking a bit weird in the app

2024-08-31 13:41 UTC, CedricCORGE commented on Application/mobile/app_code/lib/l10n/app_fr.arb
> +  "faqTitle": "Bonjour {name},\nComment pouvons-nous\nvous aider ?",
same as english

2024-09-03 10:18 UTC, 31Nathan approved these changes

2024-09-03 12:46 UTC, CedricCORGE approved these changes

2024-09-03 12:49 UTC, merged