419 web total rework of the UI
H-chauvet/RISU pull request #425
Opened 2024-09-08 18:52 UTC by H-chauvet

2024-09-11 21:28 UTC, tbellicha approved these changes

2024-09-12 08:38 UTC, invpuppet approved these changes

2024-09-13 09:59 UTC, hugolopespinto approved these changes

2024-09-14 10:11 UTC, 31Nathan requested changes
Do not push the package-lock, otherwise good

2024-09-14 10:11 UTC, 31Nathan commented on Server/package-lock.json
To not push

2024-09-14 14:31 UTC, H-chauvet commented on Server/package-lock.json
Fixed, will not be pushed anymore

2024-09-15 07:40 UTC, 31Nathan approved these changes

2024-09-15 12:16 UTC, Louismaestre approved these changes

2024-09-15 14:27 UTC, merged