408 web internationalization translation part
H-chauvet/RISU pull request #427
Opened 2024-09-12 16:56 UTC by invpuppet

All tests are working but :
- company_profil
- confirmed_user
- feedbakcs_page
- pop-up
- profile_page

2024-09-13 10:18 UTC, hugolopespinto requested changes
just some fix in the translations, but otherwise good job!

2024-09-13 10:18 UTC, hugolopespinto commented on Configurateur/front/lib/l10n/app_fr.arb
> +	"endConversation": "Cloturer la conversation",
Clôturer

2024-09-13 10:18 UTC, hugolopespinto commented on Configurateur/front/lib/l10n/app_fr.arb
> +	"orderConfirmationReturnHome": "Votre commande a bien été confirmée, vous pouvez maintenant retournez à l'accueil et nous vous contacterons dès que votre commande sera prête",
retourner

2024-09-13 10:18 UTC, hugolopespinto commented on Configurateur/front/lib/l10n/app_fr.arb
> +	"risuCompany": "L'entreprise Risu",
Risu or RISU ?

2024-09-13 10:18 UTC, hugolopespinto commented on Configurateur/front/lib/l10n/app_fr.arb
> +	"rowNumbers": "Nombres de lignes",
Nombre ?

2024-09-13 10:18 UTC, hugolopespinto commented on Configurateur/front/lib/l10n/app_en.arb
> +	"risuCompany": "Risu Company",
Risu or RISU?

2024-09-17 14:17 UTC, H-chauvet approved these changes

2024-09-17 18:48 UTC, hugolopespinto approved these changes

2024-09-17 21:20 UTC, merged