[ADD] Dark mode color rework
H-chauvet/RISU pull request #470
Opened 2024-10-15 08:24 UTC by CedricCORGE

- text English/Francais page home

- text header page "Notre équipe"

- Popup post rating, background mark, rating title

- Profile, popup input border

- shape screen, icon +/-

- progress bar, yellow dot instead of blue

- design screen, background "parcourir" in blue instead of grey

- payment screen, text color

- user/containers handling, yellow texts in tiles

2024-10-15 09:57 UTC, 31Nathan approved these changes

2024-10-15 09:59 UTC, H-chauvet approved these changes

2024-10-15 11:31 UTC, Louismaestre requested changes

2024-10-15 11:31 UTC, Louismaestre commented on Configurateur/front/lib/components/custom_popup.dart
> +                    color: Provider.of<ThemeService>(context).isDark
You should add these colors to the theme file

2024-10-16 16:19 UTC, tbellicha approved these changes

2024-10-21 17:11 UTC, Louismaestre approved these changes

2024-10-22 08:01 UTC, merged