479 mobile rent limit
H-chauvet/RISU pull request #480
Opened 2024-10-21 13:33 UTC by hugolopespinto

I added a max limit (in server and mobile app) of 24h when the user rents an article.

2024-10-21 20:30 UTC, tbellicha requested changes

2024-10-21 20:30 UTC, tbellicha commented on Server/locales/en.json
> +	"incorrectTime" : "The rental duration is incorrect (max: 24h, minimum: 1h)",
Keep it consistent, either "max" / "min" or "maximum" / "minimum"

2024-10-21 20:30 UTC, tbellicha commented on Server/locales/fr.json
> +    "incorrectTime": "Durée de location incorrecte (max: 24h, minimum: 1h)",
Keep it consistent, either "max" / "min" or "maximum" / "minimum"

2024-10-30 09:22 UTC, Tanguy-Bellicha requested changes

2024-10-30 09:22 UTC, Tanguy-Bellicha commented on Server/locales/en.json
> +	"incorrectTime" : "The rental duration is incorrect (max: 24h, mini: 1h)",
"mini" ?

2024-10-31 06:36 UTC, 31Nathan approved these changes

2024-10-31 13:12 UTC, tbellicha approved these changes

2024-11-01 14:08 UTC, merged