454 mobile add my locations and favorite in the appbar when logged in
H-chauvet/RISU pull request #484
Opened 2024-10-22 09:27 UTC by invpuppet

When Connected, 'My Rents' and 'Favorite' shown
![Screenshot_20241022_111015](https://github.com/user-attachments/assets/d66895b0-5d06-430f-b4f3-ebe485bfe231)
![Screenshot_20241022_110946](https://github.com/user-attachments/assets/30f69783-50b6-4840-acdc-8f802befea97)

Coverage Front Mobile:
![image](https://github.com/user-attachments/assets/1e73f007-2233-4996-981b-2d486055077c)

2024-10-22 09:30 UTC, Tanguy-Bellicha requested changes
Reduce size of icons and texts in the navbar

2024-10-22 09:38 UTC, H-chauvet requested changes
![image](https://github.com/user-attachments/assets/79a41138-c8c9-4d07-b3a7-cb55b988066f)
Text not fully displayed / not correctly aligned with others

2024-10-23 13:10 UTC, H-chauvet approved these changes

2024-10-23 23:21 UTC, hugolopespinto approved these changes
fix the comments of the other, and its good !

2024-10-24 00:32 UTC, merged