Translation for the FAQ's page
H-chauvet/RISU pull request #495
Opened 2024-11-11 10:01 UTC by Louismaestre

2024-11-12 08:18 UTC, H-chauvet requested changes

2024-11-12 08:18 UTC, H-chauvet commented on Configurateur/front/test/faq_test.dart
> +// }
Remove comments from code

2024-11-12 08:22 UTC, tbellicha requested changes
Add a description and screen in you PR's description

2024-11-12 08:22 UTC, tbellicha commented on Configurateur/front/lib/screens/faq/faq.dart
> +                                // '',
I guess you should remove it

2024-11-12 11:15 UTC, H-chauvet approved these changes

2024-11-13 07:42 UTC, 31Nathan approved these changes

2024-11-13 15:00 UTC, merged