Hugo/hotfix
H-chauvet/RISU pull request #509
Opened 2024-11-18 11:22 UTC by hugolopespinto

Fix "Bonjour , " --> "Bonjour, " in FAQ page
Fix crash in faq page because of missing spanish content
Update the color for the cards in the rental page and in the favorites pages

2024-11-19 16:12 UTC, Louismaestre requested changes

2024-11-19 16:12 UTC, Louismaestre commented on Application/mobile/app_code/lib/l10n/app_fr.arb
> +  "faqTitleOffline": "Bonjour, Comment pouvons-nous vous aider ?",
Why capitalize "Comment"

2024-11-19 22:50 UTC, tbellicha requested changes

2024-11-19 22:50 UTC, tbellicha commented on Application/mobile/app_code/lib/pages/faq/faq_state.dart
> +                            .faqTitle(userInformation?.firstName ?? '')
When `userInformation?.firstName` is null ?

2024-11-19 22:50 UTC, tbellicha commented on Server/prisma/schema.prisma
> +    rating          Float?                    @default(-1)
When is `rating` used ? Why are you changing it ?

2024-11-20 14:38 UTC, CedricCORGE approved these changes

2024-11-20 16:04 UTC, Louismaestre approved these changes

2024-11-20 16:28 UTC, invpuppet approved these changes

2024-11-20 16:31 UTC, merged