[ADD] Translation for company page
H-chauvet/RISU pull request #516
Opened 2024-11-19 15:49 UTC by Louismaestre

Translation for company page

2024-11-19 16:51 UTC, hugolopespinto approved these changes

2024-11-19 17:05 UTC, 31Nathan requested changes
Two french translation

2024-11-19 22:45 UTC, tbellicha approved these changes

2024-11-20 07:49 UTC, 31Nathan approved these changes

2024-11-20 08:55 UTC, merged